#!/bin/bash

#BSUB -J SRA_download          # job name
#BSUB -o SRA_download.%J.out     # Name of the job output file
#BSUB -e SRA_download.%J.error   # Name of the job error file   
#BSUB -R "rusage[mem=16GB]" #spefies the amount of memory requested
#BSUB -M 16GB #kill job if over this much memory
#BSUB -W 24:00 
# if you want to receive e-mail notifications on a non-default address
#BSUB -u hadjipas@pennmedicine.upenn.edu
### -- send notification at start --
#BSUB -B
### -- send notification at completion --
#BSUB -N

#Author: Savana Hadjipanteli
#Created: 2.10.2025

#Objective: Download publicly available files from NCBI's SRA toolkit system
#Lore: I've been trying to download the CHM13 PRO-Seq (nascent RNA) and RNA-seq data generated by the T2T consortium, which I was trying to do locally but the file transfers of this size were a bear

#####INPUT INFO

#set variable with full path to working directory you want the output from
working_dir="/project/logsdon_shared/projects/CenRNA/Short-Read"

#list SRA accessions that you want to pull files (should be the directory the original fastq is nested within)
#for me I'm getting things from the CHM13 T2T bioproject: BioProject PRJNA559484
    #RNA-Seq (rep 1): SRR15054302
    #RNA-Seq (rep 2): SRR15054301
accessions=(
    "SRR15054302"
    "SRR15054301"
)

#############

#load SRA toolkit from available modules (most recent version on cluster is 3.1.0, most recent actual version is 3.2.0)
module load sratoolkit/3.1.0

#set working directory for RNA seq
cd "$working_dir"

#set output of SRA prefetch to current working directory
vdb-config --prefetch-to-cwd

#loop through accession numbers in list
for acc in "${accessions[@]}"; do
    #prefetch sra for the accession (this is a special kind of file with accession information, about 1/17th the size of the actual fastq)
    prefetch "$acc"
    echo "prefetch of $acc complete"

    #get fastq from sra prefetched data, in the future here, if you want to specify a particular output directory add --outdir "$dest"
    #note that this requires working memory about 1.5X the size of the SRA, which is usually about 5ish Gb, so must allot enough memory for this...
    fasterq-dump "$acc" 
    echo "fastq dump of $acc complete. You should remove ${acc}.sra"
done

